### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by Xharos** [islands-wars/Docs#10]
Add our logo to docs.islandswars.fr site

**Comment by Vinetos** [comment]
Yeah, it looks so shitty without our awesome logo

**Comment by DeltaEvo** [comment]
@LightDiscord hurry up

**Comment by Xharos** [comment]
Hop hop hop benga benga
![tenor](https://user-images.githubusercontent.com/20248902/41969375-826e040e-7a07-11e8-8a5a-3adacc3a2fd3.gif)

**Comment by LightDiscord** [comment]
I'll watch this when I get home.

**Comment by Xharos** [comment]
Do it now
![source](https://user-images.githubusercontent.com/20248902/41975834-0bc73040-7a1c-11e8-9881-70ad357f9031.gif)

**Comment by Vinetos** [comment]
GO GO GO
![cn1jfl](https://user-images.githubusercontent.com/10145351/42022901-c6a31f94-7abe-11e8-90fc-aaa2304482f5.jpg)

**Comment by JesusCrie** [comment]
Bendo na bendo

**Comment by olsdavis** [comment]
tu vas le faire immediamal

**Comment by Vinetos** [comment]
hurry up
Why does it take to much time ?

**Comment by LightDiscord** [comment]
He's already here. In plain text format.

**Comment by LightDiscord** [comment]
After a discussion on the Discord with @Xharos we will add the favicon
